### ISSUE TITLE
Initializing PassportJS

### ISSUE THREAD

**Issue by nomanurrehman** [krakenjs/meddleware#26]
I am trying but failing to register PassportJS middleware in the config file. Here is the config file code for meddleware:

``` javascript
// passportjs
"passport": {
   "enabled": true,
   "priority": 92,
   "module": {
      "name": "passport",
      "method": "initialize"
   }
},
// passportjs
"passport": {
   "enabled": true,
   "priority": 93,
   "module": {
      "name": "passport",
      "method": "session"
   }
}
```

What am I doing wrong ?

**Comment by e-ayguade** [comment]
Hi, I know it's been a while, but could you explain how this fix works with Passport? Thank you.

**Comment by totherik** [comment]
My understanding was just that Passport internally depend on instance methods. Due to context not being set correctly the object instance upon which methods were being called was not the correct or expected one.
