### ISSUE TITLE
Route on middleware not working

### ISSUE THREAD

**Issue by rragan** [krakenjs/meddleware#44]
I created a yo kraken basic app to demonstrate. I added a splitTraffic middleware item to config.json and it prints out if it is ever called. It activates on the route /add (assuming I got the regex syntax straight).

Running the app and hitting /add should print the message from the middleware and the message from the route controller. All I see is the route controller. If I remove, the route on the middleware, then both show up. 

Here is the sample showing it.
https://github.com/rragan/testroute

**Comment by totherik** [comment]
Can you be more specific re: what you're testing? There are a couple of moving pieces here.

Specifically,  I can see the "route" property is working correctly with the string value `"/add"`, leading me to believe the route feature is indeed working. The regex portion, however, may be another thing...

**Comment by rragan** [comment]
Trying to add route-specific middleware to the /add route using the splitTraffic item in config.json

**Comment by totherik** [comment]
Yes, as I indicated, in my test case string routes work correctly. Are you specifically testing regex routes or does the route param not work with _any_ value for you?

**Comment by totherik** [comment]
Also, I don't see that you have a `regex` shortstop handler registered anywhere. Have you confirmed that the route value is indeed a regular expression?

**Comment by rragan** [comment]
My problem is that I thought regex: was one of the standard shortstop handlers. It is not. It is mentioned in the meddleware doc (shortstop-regex) but the link is broken (maybe fix this). I found it in npm. Lack of a handler explains it not working as it would look like a string. User error. Closing.

**Comment by totherik** [comment]
Well, one additional issue is that true regex support was added to meddleware in either v2 or v3 so may not be available in kraken 1.0 at this point. Need to confirm, however.
