### ISSUE TITLE
Events not fired properly

### ISSUE THREAD

**Issue by rapzo** [krakenjs/meddleware#50]
Is it me or all the `middleware:before` events are triggered after the middleware is loaded? I can't find a way where the `before` events are fired before registering, which, from testing, is in line with `after` events.

**Comment by jasisk** [comment]
the `middleware:before` and `middleware:after` events correspond to when middleware is registered, not when it is loaded into memory or when the factory is run (both of those will happen before the `before` events). In other words, let's say we have a middleware called `custom`. You can expect `middleware:before` (and `middleware:before:custom`) to fire, then `app.use(custom)` (or similar), then `middleware:after` (and `middleware:after:custom`).

You can see this behavior if you [log out the express:router debug statements](https://github.com/strongloop/express/blob/bbcc1e1f52cb3706660d88bc2884057d71ae1f92/lib/router/index.js#L450). For a small sample:

``` js
// ---------- index.js ----------
var meddleware = require('meddleware');
var express = require('express');
var app = express();

var config = {
  custom: {
    module: './custom'
  }
};

app.on('middleware:before:custom', function (evt) {
  console.log('before %s ...', evt.config.name);
});

app.on('middleware:after:custom', function (evt) {
  console.log('after %s ...', evt.config.name);
});

app.use(meddleware(config));

// ---------- custom.js ----------
module.exports = function customFactory() {
  return function custom(req, res, next) { next(); };
};
```

starting the above with `DEBUG=express:router node index.js` will print out:

``` sh
before custom ...
  express:router use / custom +5ms
after custom ...
```

**Comment by rapzo** [comment]
Hmmm... Ok. Thanks for in-depth example, really appreciated.
Too bad though, i was trying to inject arguments not config related using the events. Makes sense now.
Will try a different approach!
Good work guys!

**Comment by jasisk** [comment]
Hmm.. if you wouldn't mind walking me through a more specific example, maybe there's another pattern we can tease out that will work for you?

**Comment by rapzo** [comment]
Well, it's pretty simple: the process is to rig express apps with middlewares, either from modules and local, and they may require different parameters, with no pattern whatsoever. I'm looking at shortstop, looks pretty nice. Also, the config example in this module uses `"path:./lib/middleware/example.js"` but without shortstop the path is not resolved, right?
Thanks for the help o/

**Comment by jasisk** [comment]
I'd also checkout [confit](https://github.com/krakenjs/confit) to do environment-specific (or really anything specific) configs. In fact, that's precisely how we do it with [kraken-js](https://github.com/krakenjs/kraken-js).

Thanks for the heads-up on the example. You're right, [that shouldn't be in there](https://github.com/krakenjs/meddleware/pull/51).
