### ISSUE TITLE
Enabled toggle in flow controlled sections changed

### ISSUE THREAD

**Issue by jasisk** [krakenjs/meddleware#59]
~~Unconfirmed however~~ I got a report from @lmarkus that the `enabled` toggle is broken for middlewares defined in flow-control sections starting with v3.x.

**Comment by lmarkus** [comment]
Here you go...
https://github.com/lmarkus/meddlewarePOC

**Comment by jasisk** [comment]
https://github.com/krakenjs/meddleware/releases/tag/v3.0.2

Thanks for the report, @lmarkus!

**Comment by lmarkus** [comment]
Thanks for a quick fix!
