### ISSUE TITLE
`module.name` is not required?

### ISSUE THREAD

**Issue by tkambler** [krakenjs/meddleware#64]
According to the documentation, the `module.name` option is required, which makes sense. However, in Kraken's implementation, I see this:

```
"router": {
    "module": {
        "arguments": [{ "directory": "path:./controllers" }]
    }
}
```

Could someone please provide some insight into what's going on here? To what module are the arguments that we see here being passed?

**Comment by jasisk** [comment]
Hi @tkambler.

So sorry this fell off my radar.

So there are a couple of things going on here. First, one thing that [meddleware](https://github.com/krakenjs/meddleware) does and, second, one thing that [confit](https://github.com/krakenjs/confit) does (a module you're using if you're building a [kraken-js](https://github.com/krakenjs/kraken-js) app). In the example you provided, the second case is what's happening but I'll explain both for posterity.

#### The Thing that Meddleware Does™

Meddleware has a shorthand syntax for supplying the module. If you don't need to supply a method name or arguments (in other words, when the module name is sufficient), meddleware accepts a string module name for the `module` property. In other words, these two are equivalent:

``` js
{ "router": "./myFancyRouter" }
// ... is equivalent to ...
{
  "router": {
    "name": "./myFancyRouter"
  }
}
```

#### The Thing that Confit Does™

Confit is the environment-aware configuration loader we wrote for kraken-js. Each layer of configuration is loaded _on top_ of each previous layer. Objects from the new layer are merged into objects of the old layer.

Two of the config files that confit loads are `config/config.json`, followed by `config/[env].json` (`[env]` replaced with the `NODE_ENV` in which your app is run). You can think of the `config.json` as your base config, and the `[env].json` as the overlaid config that is merged into your base config. Given these files:

``` js
// config/config.json
{
  "middleware": {
    "router": {
      "module": {
        "name": "express-enrouten",
        "arguments": [{ "index": "path:./routes" }]
      }
    }
  }
}
```

``` js
// config/dev.json
{
  "middleware": {
    "router": {
      "module": {
        "arguments": [{ "directory": "path:./controllers" }]
      }
    }
  }
}
```

... your final config will look like this:

``` js
{
  "middleware": {
    "router": {
      "module": {
        "name": "express-enrouten",
        "arguments": [{ "directory": "path:./controllers" }]
      }
    }
  }
}
```

... in the case of a kraken-js app, there is a [root config](https://github.com/krakenjs/kraken-js/blob/a535bb2d33bca0c236933ebd2298f436c7befbb4/config/config.json) that gets loaded _before_ your `config/config.json` and the example above is [almost exactly the same](https://github.com/krakenjs/kraken-js/blob/a535bb2d33bca0c236933ebd2298f436c7befbb4/config/config.json#L133-L144). All of the root level configs are documented in the [kraken-js readme](https://github.com/krakenjs/kraken-js/blob/a535bb2d33bca0c236933ebd2298f436c7befbb4/README.md#included-middleware).

Let me know if anything else in unclear or if you have any other questions about this. Again, sorry for the delay!
