### ISSUE TITLE
Meddleware 4.0 not working as expected

### ISSUE THREAD

**Issue by tkambler** [krakenjs/meddleware#71]
Has something changed between meddleware 3.0.2 and meddleware 4.0 that would prevent a simple use case from working? I'm reading through the documentation and do not see anything that would indicate that this is the case.

I just spent a good amount of time tracking down the source of a problem that was preventing an application's routes from being loaded via meddleware / express-enrouten.

In my use case, meddleware's `app.once('mount', function() { ... })` never ends up firing. [Here is an example](https://dl.dropboxusercontent.com/u/832215/test.zip). Run it with:

```
$ export NODE_PATH=$NODE_PATH:./lib && node ./bin/index
```

**Comment by jasisk** [comment]
Hi tkambler,

Yes, 4.0 is a breaking change and I've not yet updated the documentation—that's my mistake.

Meddleware 4.0 introduced a new pattern of mounting on a router to avoid having to normalize routes the way we were.

There are a few things that it will break—mountpaths now work the way they do everywhere else in express, but was previously different in meddleware. Error-handling middleware is another thing that will work differently.

I'll take a look at your example and get back to you.

**Comment by jasisk** [comment]
I'm seeing `mount` fire. If you're on OS X:

``` sh
$ npm ex meddleware -- "sed -i '' '/function onmount/a\\'$'\\n''console.log(\"mounted\");' index.js" && node ./bin/index.js
Initializing Confit with configuration directory: /Users/jsisk/Downloads/test/config
ping route loaded
middleware { enrouten:
   { enabled: true,
     priority: 30,
     module: { name: 'express-enrouten', arguments: [Object] } } }
mounted
ready
App listening on port: 7025
404 - Cannot GET /api/v1/ping

```

Will keep exploring.

**Comment by jasisk** [comment]
Ok, I see the problem—I misunderstood what you were saying before.

You're absolutely right. The problem is that enrouten's `onmount` isn't fired. This is because meddleware is now a `router` instance, instead of an `app` instance. `router` instances have no analogy to `app` instances `mount` event.

I'll have to investigate how to resolve this issue. In the meantime, I recommend you move down to `^3.0.0`. If I'm unable to find a clean solution in a timely manner, I may simple deprecate 4.0.0 for now.

Thanks for bringing this to our attention—meant to spend some time on 4.x this week, you just moved it up on my list by a few items. :)

**Comment by tkambler** [comment]
What's the status on this? This bit me again for a brief moment, before I realized I'd run into this before. IMO, 4.0 should be unpublished and re-published as a -beta release. It's clearly not done.

**Comment by jasisk** [comment]
Hey @tkambler,

4.0.0 was deprecated when we spoke last. How are you installing it, exactly?

**Comment by tkambler** [comment]
`$ npm install meddleware --save`

**Comment by jasisk** [comment]
It is most certainly deprecated—are you certain you're pulling version 4.0.0?

```
❯ npm install --save meddleware
meddleware-test@1.0.0 /tmp/meddleware-test
└─┬ meddleware@3.0.3
  ├─┬ caller@0.0.1
  │ └─┬ tape@2.3.3
  │   ├── deep-equal@0.1.2
  │   ├── defined@0.0.0
  │   ├── inherits@2.0.1
  │   ├── jsonify@0.0.0
  │   ├── resumer@0.0.0
  │   └── through@2.3.8
  ├── core-util-is@1.0.2
  └── debuglog@0.0.4
```

**Comment by tkambler** [comment]
The problem seems to be a result of my using a private npm server ([Sinopia](https://github.com/rlidwka/sinopia)). Apparently I installed meddleware at a time when v4 was _not_ deprecated, which Sinopia cached (as desired). Anything you may have deprecated after that time was not picked up by the cache, however. Removing the cached version from Sinopia fixed the issue.

Sorry for the trouble.

**Comment by jasisk** [comment]
No trouble at all. Glad it all worked out.
