### ISSUE TITLE
Passing object to middleware

### ISSUE THREAD

**Issue by JohnieLee** [krakenjs/meddleware#73]
Is it possible to pass an object to the middleware via the meddleware config?

The middleware that I'm trying to implement is [jwt-redis-session](https://github.com/azuqua/jwt-redis-session).  Its constructor takes in a Redis Client object.

**Comment by jasisk** [comment]
It sure is!

Check out the [options](https://github.com/krakenjs/meddleware/tree/2b1693afddac8f77403b6be6cc7bcadbc92c3793#options) section in the README. Specifically, you're looking for the `arguments` property inside `module`.

In your case, your meddleware config should include a section that looks something like this:

``` js
"session": {
    "module": {
        "name": "jwt-redis-session",
        "arguments": [{
            // all the options you'd pass to the constructor like:
            client: redisClient,
            // ... etc ...
        }]
    }
}
```
