### ISSUE TITLE
Register middleware based on HTTP method

### ISSUE THREAD

**Issue by pea1bee** [krakenjs/meddleware#76]
I know it is possible to register middleware functions based on the route. But how do I register middleware functions based on the same route with different HTTP methods.

For example, 
/api GET will have a different set of middleware.
/api POST will have a different set of middleware.

**Comment by quarterpi** [comment]
I would also like to know if this is possible... after reading through the meddleware readme on npm it doesn't seem to be supported. What I am looking for is something like this `app.post(/\/private\/.*/, myMiddleware);`. Any thoughts?

**Comment by grawk** [comment]
You can test for the HTTP verb within any middleware and whitelist/blacklist certain verbs that way.

**Comment by quarterpi** [comment]
@grawk That is what I ended up doing. Thank you for confirming my hunch.
