### ISSUE TITLE
How can I have an environment-controllable value that defaults to true?

### ISSUE THREAD

**Issue by djMax** [krakenjs/meddleware#86]
This is easy with a default of false:

```
{
   "enable_something": "env:SOME_ENV_VAR|b",
   "meddleware": {
      "something": {    
         "enabled": "config:enable_something"
      }
   }
}
```

But how can it be arranged to default to true? This is potentially a confit/shortstop thing more than a meddleware thing, though I can see changes to any of them to fix it.

**Comment by shaunwarman** [comment]
Hey @djMax 

You're right. You'd want to use [confit](https://github.com/krakenjs/confit) to load your json configuration that uses [confit's protocol](https://github.com/krakenjs/confit#options) option to pass in your custom [shortstop](https://github.com/krakenjs/shortstop) protocol.

There is a similar setup in the tests [here](https://github.com/krakenjs/meddleware/blob/v3.x/test/meddleware.js#L45-L56), but you would want to probably take it further and have `confit` do the work of loading the json and taking advantage of your custom `shortstop` protocol. Then you can pass that object to `meddleware`.

Additionally, the `shortstop` protocol would look very similar to the default `env` handler in [shortstop-handlers](https://github.com/krakenjs/shortstop-handlers/blob/master/index.js#L86-L117).

It's late, but I'll create an example in the AM.

**Comment by shaunwarman** [comment]
So here's a simple example using a new shortstop handler:
https://github.com/shaunwarman/custom-confit-shortstop-example

This new handler would need to be passed to `confit` options like mentioned above and used to resolve your config file. Then this config object can get passed to `meddleware` at startup.

**Comment by djMax** [comment]
Yes, I can definitely see how to do it with a shortstop, but this feels like something that shouldn't require one... Basically there is support for "true" as default, but not false. Weird.
